#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

echo ""
echo "=============================="
echo "  BloatFinder"
echo "=============================="
echo ""
echo "This tool scans your disk and saves the results."
echo "The conversation about what to delete happens in Claude Code."
echo ""
echo "HOW THIS WORKS:"
echo "  Step 1 — This window scans your disk (30-60 seconds)"
echo "  Step 2 — When done, open Claude Code in this folder"
echo "  Step 3 — Say: \"let's review my disk scan\""
echo "  Step 4 — Claude walks you through everything, asks before deleting"
echo ""
echo "Starting scan now..."
echo ""

python3 bloatfinder.py

echo ""
echo "=============================="
echo "  Scan complete."
echo "=============================="
echo ""
echo "NEXT STEP:"
echo "  Open Claude Code in this folder and say:"
echo "  \"let's review my disk scan\""
echo ""
read -p "Press Enter to close this window..."
